spring:
  application:
    name: media-service
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 20
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 5000
